package api

import (
	"net/http"
	"regexp"
	"strconv"
	"strings"

	trischema "tricms/pkg/schema"
)

// fieldTypeOptions lists every supported field type in the canonical order
// (spec §3), used to populate the <select> in the Conception field builder.
// Kept in sync with the client-side mirror in web/static/js/field-builder.js.
func fieldTypeOptions() []trischema.FieldType {
	return []trischema.FieldType{
		trischema.Text, trischema.RichTextMD, trischema.RichTextHTML,
		trischema.Float, trischema.Int, trischema.Date, trischema.Media,
		trischema.Boolean, trischema.Enum, trischema.Reference,
		trischema.Slug, trischema.URL, trischema.Color, trischema.JSONType,
		trischema.GeoPoint,
	}
}

var fieldFormKeyPattern = regexp.MustCompile(`^fields\[(\d+)\]\[(\w+)\]$`)

// parseFieldsFromForm reconstructs a []trischema.Field from the
// `fields[N][prop]`-named inputs generated by the Conception field builder
// (web/static/js/field-builder.js). Rows with a blank key are skipped, so
// removed/incomplete rows don't produce invalid fields. The resulting slice
// still goes through trischema.Definition.Validate() by the caller -- this
// function only reshapes form data, it does not itself validate types.
func parseFieldsFromForm(r *http.Request) []trischema.Field {
	rows := map[int]map[string]string{}
	for key, values := range r.PostForm {
		m := fieldFormKeyPattern.FindStringSubmatch(key)
		if m == nil || len(values) == 0 {
			continue
		}
		idx, err := strconv.Atoi(m[1])
		if err != nil {
			continue
		}
		if rows[idx] == nil {
			rows[idx] = map[string]string{}
		}
		rows[idx][m[2]] = values[0]
	}

	indices := make([]int, 0, len(rows))
	for idx := range rows {
		indices = append(indices, idx)
	}
	sortInts(indices)

	fields := make([]trischema.Field, 0, len(indices))
	for _, idx := range indices {
		row := rows[idx]
		key := strings.TrimSpace(row["key"])
		if key == "" {
			continue
		}
		f := trischema.Field{
			Key:          key,
			Label:        row["label"],
			Type:         trischema.FieldType(row["type"]),
			Cardinality:  trischema.Cardinality(row["cardinality"]),
			Placeholder:  row["placeholder"],
			Required:     row["required"] == "true",
			TargetSchema: row["targetSchema"],
		}
		if opts := strings.TrimSpace(row["options"]); opts != "" {
			for _, o := range strings.Split(opts, ",") {
				if o = strings.TrimSpace(o); o != "" {
					f.Options = append(f.Options, o)
				}
			}
		}
		fields = append(fields, f)
	}
	return fields
}

func sortInts(s []int) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// FieldRowVM is the view-model for one pre-rendered row of the Conception
// field builder (used when editing an existing schema, so the initial page
// load already shows every existing field -- new rows added client-side
// pick up numbering after these).
type FieldRowVM struct {
	Index        int
	Key          string
	Label        string
	Type         trischema.FieldType
	Cardinality  trischema.Cardinality
	Required     bool
	OptionsCSV   string
	TargetSchema string
	Placeholder  string
}

// FieldRowRenderCtx bundles one row with the shared option lists its
// <select> elements need, so the "partial:field_row" template can be
// invoked with a single argument (Go's html/template only passes one).
type FieldRowRenderCtx struct {
	Row              FieldRowVM
	TypeOptions      []trischema.FieldType
	AvailableSchemas []string
}

func buildFieldRowCtxs(rows []FieldRowVM, availableSchemas []string) []FieldRowRenderCtx {
	types := fieldTypeOptions()
	out := make([]FieldRowRenderCtx, 0, len(rows))
	for _, row := range rows {
		out = append(out, FieldRowRenderCtx{Row: row, TypeOptions: types, AvailableSchemas: availableSchemas})
	}
	return out
}

func fieldsToRowVMs(fields []trischema.Field) []FieldRowVM {
	rows := make([]FieldRowVM, 0, len(fields))
	for i, f := range fields {
		rows = append(rows, FieldRowVM{
			Index:        i,
			Key:          f.Key,
			Label:        f.Label,
			Type:         f.Type,
			Cardinality:  f.Cardinality,
			Required:     f.Required,
			OptionsCSV:   strings.Join(f.Options, ","),
			TargetSchema: f.TargetSchema,
			Placeholder:  f.Placeholder,
		})
	}
	return rows
}
